name: CI/CD for master

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ü™ê Do a full test for this project.
        run: auto/test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
    - name: üõ´ executing remote ssh commands using ssh key
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd ~/scaffold-springboot-gradle
          git pull origin master
          echo Pulling newest code from github.
          docker-compose down
          echo Shutdown original server
          docker-compose run -d app
          echo Server started...


